### PR TITLE
Adjust to new JSON format for Snapcast 0.11

### PR DESCRIPTION
**Pull request by 1337sup3rh4x0r**
updating readings works again
ToDo:
- setting volume and mute needs update 
- setting stream needs update -> now set via group, not via client

### CODE REVIEW

**Comment by 1337sup3rh4x0r** [comment]
ToDos from above closed

**Comment by twenta** [comment]
I get the following errors:
2017.06.17 00:31:37 1: PERL WARNING: Use of uninitialized value in hash element at ./FHEM/96_Snapcast.pm line 246.
2017.06.17 00:31:37 1: PERL WARNING: Use of uninitialized value in string ne at ./FHEM/96_Snapcast.pm line 438.

**Comment by 1337sup3rh4x0r** [comment]
Those are not errors but warnings. 
The module will work nonetheless. 
I couldn't figure out how to get rid of these warnings since I basically don't speak perl.

**Comment by twenta** [comment]
Ok, but in addition the readings were not updated after first read. Not sure if this is somehow related... I will further look into this...

**Comment by unimatrix27** [comment]
Hi guys, thanks for looking into this. I wont have a lot of time during the next days, but if you come up with a version that works and tested, I can put it to the FHEM SVN.

**Comment by 1337sup3rh4x0r** [comment]
Thank you for providing the basis in the first place.

For me this version has been working for a couple of days now with two minor issues:
1. The warnings that twenta mentioned
2. The for loop, starting at line 233, that you intended to allow evaluating several lines if the buffer contains more than one line somehow doesn't work. It always only evaluates the first line. I am guessing that this might be due to one of the "return" commands aborting not only the inner if-condition but the whole outer loop as well. But I must admit I don't fully understand how perl works here. That's something you might want to look in to if you find the time :)
To work around this, I have to place "sleep 0.5" commands between snapcast fhem commands whenever I want to issue multiple commands in a row (e.g. unmute and change stream on notify).

Also I may not have adhered to your style everywhere.

And I fear that I have disabled your volume constraint function (starting line 276) since that was giving me problems.

**Pull request merged**
